version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - export AWS_REGION=us-east-1
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 683746102303.dkr.ecr.${AWS_REGION}.amazonaws.com
      - REPOSITORY_URI=683746102303.dkr.ecr.us-east-1.amazonaws.com/api
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
    - echo Build completed on date
    - echo Pushing Docker image...
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - cat Dockerrun.aws.json | sed  -e "s#@@IMAGE_TAG@@#$IMAGE_TAG#g" > /tmp/Dockerrun.aws.json
    - export stage=testenvvar
    - export REGION=us-east-1
    - export docker_tag_version=$IMAGE_TAG
    - export app_short_name=api
    - export bucketname="elasticbeanstalk-us-east-1-683746102303"
    - export env_name="eb-$stage-$stage-$app_short_name"
    - export objectkey="$stage-app-name-$app_short_name.zip"
    - export app_name="$stage-app-name-$app_short_name"
    - zip -j "$objectkey" /tmp/Dockerrun.aws.json
    - aws s3 cp $objectkey s3://$bucketname/$objectkey
    - aws elasticbeanstalk create-application-version --application-name $app_name --version-label $docker_tag_version --source-bundle S3Bucket=$bucketname,S3Key=$objectkey
    - aws --region $REGION elasticbeanstalk update-environment --environment-name $env_name --version-label $docker_tag_version
